const Questions = [
  {
    type: "math",
    question: "What is 5 + 7?",
    options: ["10", "12", "15"],
    answer: "12",
  },
  {
    type: "math",
    question: "What is the square root of 81?",
    options: ["9", "8", "7"],
    answer: "9",
  },
  {
    type: "math",
    question: "What is 3 × 4?",
    options: ["6", "12", "9"],
    answer: "12",
  },
  {
    type: "physics",
    question: "What is the unit of force?",
    options: ["Joule", "Pascal", "Newton"],
    answer: "Newton",
  },
  {
    type: "physics",
    question: "What is the speed of light?",
    options: ["300,000 km/s", "150,000 km/s", "450,000 km/s"],
    answer: "300,000 km/s",
  },
  {
    type: "physics",
    question: "Which particle has a negative charge?",
    options: ["Electron", "Proton", "Neutron"],
    answer: "Electron",
  },
  {
    type: "general",
    question: "What planet is known as the Red Planet?",
    options: ["Mars", "Venus", "Jupiter"],
    answer: "Mars",
  },
  {
    type: "general",
    question: "What is the capital of France?",
    options: ["Paris", "London", "Berlin"],
    answer: "Paris",
  },
  {
    type: "general",
    question: "What is H2O commonly known as?",
    options: ["Salt", "Water", "Air"],
    answer: "Water",
  },
  {
    type: "riddle",
    question: "What has keys but can’t open locks?",
    options: ["Piano", "Door", "Map"],
    answer: "Piano",
  },
  {
    type: "riddle",
    question: "What has a head and a tail but no body?",
    options: ["Coin", "Snake", "Bottle"],
    answer: "Coin",
  },
  {
    type: "riddle",
    question: "What gets wetter the more it dries?",
    options: ["Towel", "Sun", "Rain"],
    answer: "Towel",
  },
  {
    type: "math",
    question: "What is 15 ÷ 3?",
    options: ["5", "4", "6"],
    answer: "5",
  },
  {
    type: "math",
    question: "What is 2²?",
    options: ["2", "4", "6"],
    answer: "4",
  },
  {
    type: "math",
    question: "What is 100 - 45?",
    options: ["55", "65", "60"],
    answer: "55",
  },
  {
    type: "physics",
    question: "What is the unit of electrical resistance?",
    options: ["Ohm", "Watt", "Volt"],
    answer: "Ohm",
  },
  {
    type: "physics",
    question: "Which force keeps planets in orbit?",
    options: ["Magnetism", "Gravity", "Electricity"],
    answer: "Gravity",
  },
  {
    type: "physics",
    question: "What does a thermometer measure?",
    options: ["Heat", "Speed", "Temperature"],
    answer: "Temperature",
  },
  {
    type: "general",
    question: "What language is primarily spoken in Brazil?",
    options: ["Spanish", "Portuguese", "French"],
    answer: "Portuguese",
  },
  {
    type: "general",
    question: "What currency is used in Japan?",
    options: ["Yen", "Won", "Dollar"],
    answer: "Yen",
  },
  {
    type: "general",
    question: "Which animal is known as the King of the Jungle?",
    options: ["Lion", "Tiger", "Elephant"],
    answer: "Lion",
  },
  {
    type: "riddle",
    question: "I speak without a mouth and hear without ears. What am I?",
    options: ["Echo", "Shadow", "Wind"],
    answer: "Echo",
  },
  {
    type: "riddle",
    question: "The more you take, the more you leave behind. What are they?",
    options: ["Footsteps", "Coins", "Books"],
    answer: "Footsteps",
  },
  {
    type: "riddle",
    question: "What comes down but never goes up?",
    options: ["Rain", "Smoke", "Age"],
    answer: "Rain",
  },
  {
    type: "math",
    question: "What is 9 × 6?",
    options: ["54", "63", "45"],
    answer: "54",
  },
  {
    type: "math",
    question: "What is the cube root of 27?",
    options: ["3", "9", "6"],
    answer: "3",
  },
  {
    type: "math",
    question: "What is 14 + 5?",
    options: ["19", "20", "21"],
    answer: "19",
  },
  {
    type: "physics",
    question: "Which of these is a renewable energy source?",
    options: ["Coal", "Solar", "Oil"],
    answer: "Solar",
  },
  {
    type: "physics",
    question: "What is the boiling point of water at sea level?",
    options: ["100°C", "90°C", "110°C"],
    answer: "100°C",
  },
  {
    type: "physics",
    question: "What color does a red apple appear under green light?",
    options: ["Black", "Green", "Red"],
    answer: "Black",
  },
  {
    type: "general",
    question: "What is the largest ocean on Earth?",
    options: ["Atlantic", "Indian", "Pacific"],
    answer: "Pacific",
  },
  {
    type: "general",
    question: "How many continents are there?",
    options: ["5", "6", "7"],
    answer: "7",
  },
  {
    type: "general",
    question: "Who wrote 'Romeo and Juliet'?",
    options: ["Shakespeare", "Homer", "Dickens"],
    answer: "Shakespeare",
  },
  {
    type: "riddle",
    question:
      "What can travel around the world while staying in the same corner?",
    options: ["Stamp", "Map", "Clock"],
    answer: "Stamp",
  },
  {
    type: "riddle",
    question: "What has hands but can’t clap?",
    options: ["Clock", "Robot", "Chair"],
    answer: "Clock",
  },
  {
    type: "riddle",
    question: "I have branches but no fruit, trunk, or leaves. What am I?",
    options: ["Bank", "Tree", "River"],
    answer: "Bank",
  },
  {
    type: "math",
    question: "What is 8 × 7?",
    options: ["56", "48", "64"],
    answer: "56",
  },
  {
    type: "math",
    question: "What is 100 ÷ 5?",
    options: ["20", "25", "15"],
    answer: "20",
  },
  {
    type: "math",
    question: "What is the next prime number after 7?",
    options: ["9", "11", "13"],
    answer: "11",
  },
  {
    type: "math",
    question: "What is the perimeter of a square with side 6?",
    options: ["24", "36", "12"],
    answer: "24",
  },
  {
    type: "math",
    question: "What is 45% of 200?",
    options: ["90", "80", "70"],
    answer: "90",
  },
  {
    type: "math",
    question: "What is the value of π (pi) to 2 decimal places?",
    options: ["3.14", "3.13", "3.15"],
    answer: "3.14",
  },
  {
    type: "physics",
    question: "Which state of matter has no fixed shape but a fixed volume?",
    options: ["Solid", "Liquid", "Gas"],
    answer: "Liquid",
  },
  {
    type: "physics",
    question: "Which instrument is used to measure electric current?",
    options: ["Voltmeter", "Ammeter", "Thermometer"],
    answer: "Ammeter",
  },
  {
    type: "physics",
    question: "Which of the following is NOT a vector quantity?",
    options: ["Velocity", "Force", "Speed"],
    answer: "Speed",
  },
  {
    type: "physics",
    question: "What color has the longest wavelength in the visible spectrum?",
    options: ["Red", "Blue", "Green"],
    answer: "Red",
  },
  {
    type: "physics",
    question: "What causes tides on Earth?",
    options: ["Wind", "Moon's gravity", "Earth’s rotation"],
    answer: "Moon's gravity",
  },
  {
    type: "physics",
    question: "What is measured in Hertz?",
    options: ["Frequency", "Voltage", "Current"],
    answer: "Frequency",
  },
  {
    type: "general",
    question: "Who painted the Mona Lisa?",
    options: ["Leonardo da Vinci", "Picasso", "Michelangelo"],
    answer: "Leonardo da Vinci",
  },
  {
    type: "general",
    question: "Which gas do plants absorb from the atmosphere?",
    options: ["Oxygen", "Carbon Dioxide", "Nitrogen"],
    answer: "Carbon Dioxide",
  },
  {
    type: "general",
    question: "In which country is the Great Pyramid of Giza?",
    options: ["Mexico", "Greece", "Egypt"],
    answer: "Egypt",
  },
  {
    type: "general",
    question: "Which is the longest river in the world?",
    options: ["Amazon", "Nile", "Yangtze"],
    answer: "Nile",
  },
  {
    type: "general",
    question: "What is the main ingredient in guacamole?",
    options: ["Avocado", "Tomato", "Lettuce"],
    answer: "Avocado",
  },
  {
    type: "general",
    question: "How many legs does a spider have?",
    options: ["6", "8", "10"],
    answer: "8",
  },
  {
    type: "riddle",
    question:
      "What comes once in a minute, twice in a moment, but never in a thousand years?",
    options: ["The letter M", "Time", "Sunrise"],
    answer: "The letter M",
  },
  {
    type: "riddle",
    question: "What can fill a room but takes up no space?",
    options: ["Light", "Air", "Music"],
    answer: "Light",
  },
  {
    type: "riddle",
    question: "What is so fragile that saying its name breaks it?",
    options: ["Silence", "Glass", "Secret"],
    answer: "Silence",
  },
  {
    type: "riddle",
    question: "What has to be broken before you can use it?",
    options: ["Egg", "Seal", "Lock"],
    answer: "Egg",
  },
  {
    type: "riddle",
    question: "I’m tall when I’m young, and I’m short when I’m old. What am I?",
    options: ["Candle", "Tree", "Human"],
    answer: "Candle",
  },
  {
    type: "riddle",
    question: "What can you catch but not throw?",
    options: ["Cold", "Ball", "Shadow"],
    answer: "Cold",
  },
  {
    type: "math",
    question: "What is the median of 3, 7, 9?",
    options: ["7", "5", "9"],
    answer: "7",
  },
  {
    type: "math",
    question: "What is 0.25 as a fraction?",
    options: ["1/4", "1/2", "1/5"],
    answer: "1/4",
  },
  {
    type: "math",
    question: "What is the area of a triangle with base 10 and height 5?",
    options: ["25", "30", "20"],
    answer: "25",
  },
  {
    type: "math",
    question: "What is 2 to the power of 5?",
    options: ["32", "16", "64"],
    answer: "32",
  },
  {
    type: "physics",
    question: "Which of these is not a fundamental force?",
    options: ["Friction", "Gravitational", "Electromagnetic"],
    answer: "Friction",
  },
  {
    type: "physics",
    question:
      "What happens to the pressure of a gas if volume decreases and temperature remains constant?",
    options: ["Increases", "Decreases", "Stays the same"],
    answer: "Increases",
  },
  {
    type: "physics",
    question:
      "What is the scientific term for materials that do not allow electricity to flow?",
    options: ["Insulators", "Conductors", "Resistors"],
    answer: "Insulators",
  },
  {
    type: "general",
    question: "Which planet is closest to the sun?",
    options: ["Mercury", "Venus", "Earth"],
    answer: "Mercury",
  },
  {
    type: "general",
    question: "Who invented the telephone?",
    options: ["Alexander Graham Bell", "Thomas Edison", "Nikola Tesla"],
    answer: "Alexander Graham Bell",
  },
  {
    type: "general",
    question: "Which continent is the Sahara Desert located on?",
    options: ["Africa", "Asia", "Australia"],
    answer: "Africa",
  },
  {
    type: "riddle",
    question: "I shave every day, but my beard stays the same. What am I?",
    options: ["Barber", "Mirror", "Photograph"],
    answer: "Barber",
  },
  {
    type: "riddle",
    question: "The more of me you take, the more you leave behind. What am I?",
    options: ["Footsteps", "Time", "Air"],
    answer: "Footsteps",
  },
  {
    type: "riddle",
    question: "What invention lets you look right through a wall?",
    options: ["Window", "Door", "Camera"],
    answer: "Window",
  },
];

export default Questions;
