const Questions = [
  {
    type: "math",
    question: "What is 5 + 7?",
    options: ["10", "12", "15"],
    answer: "12",
  },
  {
    type: "math",
    question: "What is the square root of 81?",
    options: ["9", "8", "7"],
    answer: "9",
  },
  {
    type: "math",
    question: "What is 3 × 4?",
    options: ["6", "12", "9"],
    answer: "12",
  },
  {
    type: "physics",
    question: "What is the unit of force?",
    options: ["Joule", "Pascal", "Newton"],
    answer: "Newton",
  },
  {
    type: "physics",
    question: "What is the speed of light?",
    options: ["300,000 km/s", "150,000 km/s", "450,000 km/s"],
    answer: "300,000 km/s",
  },
  {
    type: "physics",
    question: "Which particle has a negative charge?",
    options: ["Electron", "Proton", "Neutron"],
    answer: "Electron",
  },
  {
    type: "general",
    question: "What planet is known as the Red Planet?",
    options: ["Mars", "Venus", "Jupiter"],
    answer: "Mars",
  },
  {
    type: "general",
    question: "What is the capital of France?",
    options: ["Paris", "London", "Berlin"],
    answer: "Paris",
  },
  {
    type: "general",
    question: "What is H2O commonly known as?",
    options: ["Salt", "Water", "Air"],
    answer: "Water",
  },
  {
    type: "riddle",
    question: "What has keys but can’t open locks?",
    options: ["Piano", "Door", "Map"],
    answer: "Piano",
  },
  {
    type: "riddle",
    question: "What has a head and a tail but no body?",
    options: ["Coin", "Snake", "Bottle"],
    answer: "Coin",
  },
  {
    type: "riddle",
    question: "What gets wetter the more it dries?",
    options: ["Towel", "Sun", "Rain"],
    answer: "Towel",
  },
  {
    type: "math",
    question: "What is 15 ÷ 3?",
    options: ["5", "4", "6"],
    answer: "5",
  },
  {
    type: "math",
    question: "What is 2²?",
    options: ["2", "4", "6"],
    answer: "4",
  },
  {
    type: "math",
    question: "What is 100 - 45?",
    options: ["55", "65", "60"],
    answer: "55",
  },
  {
    type: "physics",
    question: "What is the unit of electrical resistance?",
    options: ["Ohm", "Watt", "Volt"],
    answer: "Ohm",
  },
  {
    type: "physics",
    question: "Which force keeps planets in orbit?",
    options: ["Magnetism", "Gravity", "Electricity"],
    answer: "Gravity",
  },
  {
    type: "physics",
    question: "What does a thermometer measure?",
    options: ["Heat", "Speed", "Temperature"],
    answer: "Temperature",
  },
  {
    type: "general",
    question: "What language is primarily spoken in Brazil?",
    options: ["Spanish", "Portuguese", "French"],
    answer: "Portuguese",
  },
  {
    type: "general",
    question: "What currency is used in Japan?",
    options: ["Yen", "Won", "Dollar"],
    answer: "Yen",
  },
  {
    type: "general",
    question: "Which animal is known as the King of the Jungle?",
    options: ["Lion", "Tiger", "Elephant"],
    answer: "Lion",
  },
  {
    type: "riddle",
    question: "I speak without a mouth and hear without ears. What am I?",
    options: ["Echo", "Shadow", "Wind"],
    answer: "Echo",
  },
  {
    type: "riddle",
    question: "The more you take, the more you leave behind. What are they?",
    options: ["Footsteps", "Coins", "Books"],
    answer: "Footsteps",
  },
  {
    type: "riddle",
    question: "What comes down but never goes up?",
    options: ["Rain", "Smoke", "Age"],
    answer: "Rain",
  },
  {
    type: "math",
    question: "What is 9 × 6?",
    options: ["54", "63", "45"],
    answer: "54",
  },
  {
    type: "math",
    question: "What is the cube root of 27?",
    options: ["3", "9", "6"],
    answer: "3",
  },
  {
    type: "math",
    question: "What is 14 + 5?",
    options: ["19", "20", "21"],
    answer: "19",
  },
  {
    type: "physics",
    question: "Which of these is a renewable energy source?",
    options: ["Coal", "Solar", "Oil"],
    answer: "Solar",
  },
  {
    type: "physics",
    question: "What is the boiling point of water at sea level?",
    options: ["100°C", "90°C", "110°C"],
    answer: "100°C",
  },
  {
    type: "physics",
    question: "What color does a red apple appear under green light?",
    options: ["Black", "Green", "Red"],
    answer: "Black",
  },
  {
    type: "general",
    question: "What is the largest ocean on Earth?",
    options: ["Atlantic", "Indian", "Pacific"],
    answer: "Pacific",
  },
  {
    type: "general",
    question: "How many continents are there?",
    options: ["5", "6", "7"],
    answer: "7",
  },
  {
    type: "general",
    question: "Who wrote 'Romeo and Juliet'?",
    options: ["Shakespeare", "Homer", "Dickens"],
    answer: "Shakespeare",
  },
  {
    type: "riddle",
    question:
      "What can travel around the world while staying in the same corner?",
    options: ["Stamp", "Map", "Clock"],
    answer: "Stamp",
  },
  {
    type: "riddle",
    question: "What has hands but can’t clap?",
    options: ["Clock", "Robot", "Chair"],
    answer: "Clock",
  },
  {
    type: "riddle",
    question: "I have branches but no fruit, trunk, or leaves. What am I?",
    options: ["Bank", "Tree", "River"],
    answer: "Bank",
  },
];

export default Questions;
